### ISSUE TITLE
Change the login page title

### ISSUE THREAD

**Issue by savindumahasen** [gajindubandara/library-managment-system#22]
**Is your feature request related to a problem? Please describe.**
the login page title should be changed

**Describe the solution you'd like**
The login page title changed into the member login

**Are you working on it?**
Yes

**Comment by gajindubandara** [comment]
Keep the login page title as it is. Add a header to the main content of the page as "Login" .Get an idea from the other pages. Use the same styles as in other pages to maintain the page consistency
