### ISSUE TITLE
Create manage user page

### ISSUE THREAD

**Issue by gajindubandara** [gajindubandara/library-managment-system#5]
**Is your feature request related to a problem? Please describe.**
The system does not have the features to manage the users

**Describe the solution you'd like**
Create a separate page for the admin to manage users (add/view/change state)

**Are you working on it?**
No

**Comment by sandun7787** [comment]
is this finish

**Comment by gajindubandara** [comment]
> is this finish

No! You can start working on this @sandun7787

**Comment by sandun7787** [comment]
Tomorrow  i will finihs this
